on:
  push:
    branches:
    - master
    - develop
    - staging
jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['18.x']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: yarn, test lint formatter, and build step
        run: yarn
      - name: prettier fix
        run: yarn lint:prettier-fix
      - name: eslint fix
        run: yarn lint:eslint-fix
      - name: editorconfig checks
        run: yarn test:editorconfig
      - name: stylelint
        run: yarn lint:styles-fix
      - name: unit tests react testing library
        run: yarn vitest run
      - name: build step
        run: yarn build
