on:
    pull_request:
        branches:
            - develop
jobs:
    build_and_test:
        name: build and test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version: ['18.x']
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - name: yarn, test lint formatter, and build step
              run: yarn
            - name: prettier fix
              run: yarn lint:prettier-fix
            - name: eslint fix
              run: yarn lint:eslint-fix
            - name: editorconfig checks
              run: yarn test:editorconfig
            - name: stylelint
              run: yarn lint:styles-fix
            - name: unit tests react testing library
              run: yarn vitest run
            - name: build step
              run: yarn build
    deploy:
        name: deploy to aws s-3 and cloudfront
        environment: Development
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn

            - name: Build
              run: yarn build

            - name: Deploy
              uses: reggionick/s3-deploy@v3
              with:
                  folder: build
                  bucket: ${{ vars.AWS_DEV_BUCKET_NAME }}
                  bucket-region: ${{ vars.AWS_BUCKET_REGION }}
                  dist-id: ${{ secrets.AWS_CLOUDFRONT_DEVELOPMENT_ID }}
                  invalidation: /
                  delete-removed: true
                  no-cache: true
                  private: true
                  files-to-include: '.*/*,*/*,**'
